### ISSUE TITLE
How to run, or use?

### ISSUE THREAD

**Issue by CharaTheFallen** [JamesMcMahon/monocle-engine#2]
I want to use this to run some of the c# code I have. How do I run this?

**Comment by JamesMcMahon** [comment]
I honestly have no idea, I just mirrored it from the original repo, which appears to be gone now.

I believe there are newer mirrors out there, check out https://github.com/shortgecko/MonocleEngineMirror (which may or may not be newer, hard to tell because they didn't maintain the original commits). You may want to try and message Maddy and see where she is keeping her repos currently. If you end up finding the original repo let me know and I will update this repo with a link.

**Comment by JamesMcMahon** [comment]
This may be helpful as well, https://github.com/dacher996/MonocleEngineDemo.
